#pragma once

constexpr UINT MAX_BONE_MATRIX        = 128;
constexpr UINT SWAPCHAIN_BUFFER_COUNT = 4;
constexpr UINT MAX_DIRECTIONAL_LIGHT  = 4;
constexpr UINT MAX_POINT_LIGHT        = 32;
constexpr UINT MAX_SPOT_LIGHT         = 16;
constexpr UINT MAX_LIGHT              = MAX_DIRECTIONAL_LIGHT + MAX_POINT_LIGHT + MAX_SPOT_LIGHT;

enum class FeatureLevel { LEVEL_11_0, LEVEL_12_0, LEVEL_12_1 };

enum class ResourceType { MODEL, TEXTURE, ANIMATION };

enum class CommandType { DIRECT, BUNDLE, COMPUTE};

enum FenceType { MESH_COMPUTE_FENCE, PARTICLE_COMPUTE_FENCE,MESH_RENDER_FENCE, PARTICLE_RENDER_FENCE, FENCE_END };

enum CommandListType { MESH_COMPUTE_LIST,MESH_RENDER_LIST,PARTICLE_COMPUTE_LIST,PARTICLE_RENDER_LIST, IMGUI_RENDER_LIST, COMMAND_LIST_END};

enum class MeshRenderType { STATIC, SKELETAL, };