#pragma once

constexpr UINT SWAPCHAIN_BUFFER_COUNT = 4;

enum class FEATURE_LEVEL { LEVEL_11_0, LEVEL_12_0, LEVEL_12_1 };

enum RESOURCE { IB, VB, CB, DS, RT, SR, END };

enum class RESOURCE_TYPE { MODEL, TEXTURE, ANIMATION };

enum class COMMAND_TYPE { DIRECT, BUNDLE, COMPUTE};

enum FENCE_TYPE { MESH_COMPUTE_FENCE, PARTICLE_COMPUTE_FENCE,MESH_RENDER_FENCE, PARTICLE_RENDER_FENCE, FENCE_END };

enum COMMAND_LIST_TYPE {MESH_COMPUTE_LIST,MESH_RENDER_LIST,PARTICLE_COMPUTE_LIST,PARTICLE_RENDER_LIST,COMMAND_LIST_END};