#Requires -Version 5.1

<#
.SYNOPSIS
    Scans a directory for shader files and generates C++ header files for
    shader type enums and enum-to-filename mappings.
#>

param (
    [string]$ShaderDirectory = (Join-Path $PSScriptRoot '..\..\Shaders'),
    [string]$HeaderFile = (Join-Path $PSScriptRoot '..\ShaderTypes.h')
)

function Generate-ShaderFiles {
    Write-Host "Starting shader file generation process..."

    $outputEnumFile = $HeaderFile -replace '\.h$', '.generated.h'
    $outputMapFile = $HeaderFile -replace '\.h$', '.Mappings.generated.h'
    Write-Host "Enum header will be generated to: $outputEnumFile"
    Write-Host "Mapping header will be generated to: $outputMapFile"

    $headerTemplate = @"
#pragma once

// This file is auto-generated. DO NOT EDIT.

namespace GE
{
    enum class VS { NONE, END };
    enum class PS { NONE, END };
    enum class CS { NONE, END };
    enum class GS { NONE, END };
    enum class HS { NONE, END };
    enum class DS { NONE, END };
}
"@

    $headerContent = if (Test-Path $HeaderFile) { Get-Content -Path $HeaderFile -Raw -Encoding UTF8 } else { $headerTemplate }
    $originalContent = $headerContent

    try {
        $shaderFiles = Get-ChildItem -Path $ShaderDirectory -Filter *.hlsli -Recurse
        $shaderFiles += Get-ChildItem -Path $ShaderDirectory -Filter *.hlsl -Recurse
    } catch {
        Write-Error "Error reading shader directory: $_"
        return
    }

    $shaderPrefixes = @{
        "VS" = "vs_";
        "PS" = "ps_";
        "GS" = "gs_";
        "HS" = "hs_";
        "DS" = "ds_";
        "CS" = "cs_"
    }

    $enumToFileMap = @{}

    foreach ($enumName in $shaderPrefixes.Keys) {
        $prefix = $shaderPrefixes[$enumName]
        $enumRegex = [regex]"(?s)(enum\s+class\s+$enumName\s*\{\s*)([\s\S]*?)(\s*};)"
        $match = $enumRegex.Match($headerContent)

        if (-not $match.Success) { continue }

        $enumBody = $match.Groups[2].Value
        $existingEnums = $enumBody.Split([Environment]::NewLine) | ForEach-Object { $_.Trim() -replace ",", "" -split "//" | Select-Object -First 1 -ExpandProperty Trim } | Where-Object { $_ -ne "" -and $_ -ne "NONE" -and $_ -ne "END" }

        $newEnums = [System.Collections.Generic.List[string]]@()
        $enumToFileMap[$enumName] = @{}

        foreach ($fileInfo in $shaderFiles) {
            $filename = $fileInfo.Name
            if ($filename.StartsWith($prefix)) {
                $baseName = [System.IO.Path]::GetFileNameWithoutExtension($filename).Substring($prefix.Length)
                if ([string]::IsNullOrWhiteSpace($baseName)) { continue }
                $enumValue = $baseName.ToUpper()
                
                $enumToFileMap[$enumName][$enumValue] = $filename

                if ($enumValue -notin $existingEnums) { $newEnums.Add($enumValue) }
            }
        }

        if ($newEnums.Count -gt 0) {
            $allEnumsForType = $existingEnums + $newEnums
            $sortedEnums = $allEnumsForType | Sort-Object -Unique

            $newBodyString = "`n        NONE,`n"
            foreach ($enum in $sortedEnums) { $newBodyString += "        {0},`n" -f $enum }
            $newBodyString += "        END`n    "
            $newFullBlock = "{0}{1}{2}" -f $match.Groups[1].Value, $newBodyString, $match.Groups[3].Value
            $headerContent = $headerContent.Replace($match.Groups[0].Value, $newFullBlock)
        }
    }

    # --- Generate Enum Header File ---
    if ($headerContent -ne $originalContent) {
        Set-Content -Path $outputEnumFile -Value $headerContent -Encoding UTF8 -NoNewline
        Write-Host "Successfully generated enum header file: $outputEnumFile" -ForegroundColor Green
    } else {
        Write-Host "No new enums found. Enum header is up-to-date." -ForegroundColor Yellow
    }

    # --- Generate Mapping Header File ---
    $mapFileContent = @"
#pragma once

// This file is auto-generated by update_shaders.ps1. DO NOT EDIT.

#include "ShaderTypes.generated.h"
#include <string>
#include <unordered_map>

namespace GE
{
"@

    foreach ($enumName in $enumToFileMap.Keys) {
        $fileNameMapName = "enumTo" + $enumName + "FileNameMap"
        $fileNameMapContent = "    inline const std::unordered_map<${enumName}, std::wstring> ${fileNameMapName} = {`n"
        
        $globalNameToEnumMapName = "globalNameTo" + $enumName + "EnumMap"
        $globalNameToEnumMapContent = "    inline const std::unordered_map<std::wstring, ${enumName}> ${globalNameToEnumMapName} = {`n"

        $enumToGlobalNameMapName = "enumTo" + $enumName + "GlobalNameMap"
        $enumToGlobalNameMapContent = "    inline const std::unordered_map<${enumName}, std::wstring> ${enumToGlobalNameMapName} = {`n"

        foreach ($entry in $enumToFileMap[$enumName].GetEnumerator()) {
            $enumValue = $entry.Key
            $fileName = $entry.Value
            $baseName = [System.IO.Path]::GetFileNameWithoutExtension($fileName)
            $globalName = "g_" + $baseName

            $fileNameMapContent += "        {${enumName}::${enumValue}, L`"${fileName}`"},`n"
            
            $globalNameToEnumMapContent += "        {L`"${globalName}`", ${enumName}::${enumValue}},`n"

            $enumToGlobalNameMapContent += "        {${enumName}::${enumValue}, L`"${globalName}`"},`n"
        }

        $fileNameMapContent = $fileNameMapContent.TrimEnd(",`n") + "`n"
        $fileNameMapContent += "    };`n`n"

        $globalNameToEnumMapContent = $globalNameToEnumMapContent.TrimEnd(",`n") + "`n"
        $globalNameToEnumMapContent += "    };`n`n"

        $enumToGlobalNameMapContent = $enumToGlobalNameMapContent.TrimEnd(",`n") + "`n"
        $enumToGlobalNameMapContent += "    };`n`n"

        $mapFileContent += $fileNameMapContent
        $mapFileContent += $globalNameToEnumMapContent
        $mapFileContent += $enumToGlobalNameMapContent
    }

    $mapFileContent += "}
"

    Set-Content -Path $outputMapFile -Value $mapFileContent -Encoding UTF8 -NoNewline
    Write-Host "Successfully generated mapping header file: $outputMapFile" -ForegroundColor Green


    # --- Generate Shader Bytecode Helper Header ---
    $bytecodeHeaderPath = $HeaderFile -replace 'ShaderTypes\.h$', 'ShaderBytecode.generated.h'
    Write-Host "Bytecode helper header will be generated to: $bytecodeHeaderPath"

    $bytecodeContent = @"
#pragma once

// This file is auto-generated by update_shaders.ps1. DO NOT EDIT.

#include "ShaderTypes.generated.h"
#include "Shaders/CompiledShaders.h"
#include <d3d12.h>

namespace GE
{
"@

    foreach ($enumName in $shaderPrefixes.Keys) {
        if ($enumToFileMap.ContainsKey($enumName) -and $enumToFileMap[$enumName].Count -gt 0) {
            $bytecodeContent += @"

    inline D3D12_SHADER_BYTECODE GetShaderBytecode($enumName shader)
    {
        switch (shader)
        {
"@
            foreach ($entry in $enumToFileMap[$enumName].GetEnumerator() | Sort-Object Key) {
                $enumValue = $entry.Key
                $fileName = $entry.Value
                $baseName = [System.IO.Path]::GetFileNameWithoutExtension($fileName)
                $arrayName = "g_" + $baseName
                $bytecodeContent += "            case ${enumName}::${enumValue}: return { ${arrayName}, sizeof(${arrayName}) };`n"
            }

            $bytecodeContent += @"
            default: return { nullptr, 0 };
        }
    }
"@
        }
    }

    $bytecodeContent += @"
}
"@

    Set-Content -Path $bytecodeHeaderPath -Value $bytecodeContent -Encoding UTF8 -NoNewline
    Write-Host "Successfully generated shader bytecode helper header file: $bytecodeHeaderPath" -ForegroundColor Green
}

# --- Execution ---
Generate-ShaderFiles