#Requires -Version 5.1

<#
.SYNOPSIS
    Scans a directory for shader files and generates C++ header files for
    shader type enums and enum-to-filename mappings.
#>

param (
    [string]$ShaderDirectory = (Join-Path $PSScriptRoot '..\Source\GA6thFinal_Framework\Shaders'),
    [string]$HeaderFile = (Join-Path $PSScriptRoot '..\Source\GA6thFinal_Framework\GraphicsEngine\ShaderTypes.h')
)

function Generate-ShaderFiles {
    Write-Host "Starting shader file generation process..."

    $outputEnumFile = $HeaderFile -replace '\.h$', '.generated.h'
    $outputMapFile = $HeaderFile -replace '\.h$', '.Mappings.generated.h'
    Write-Host "Enum header will be generated to: $outputEnumFile"
    Write-Host "Mapping header will be generated to: $outputMapFile"

    $headerTemplate = @"
#pragma once

// This file is auto-generated. DO NOT EDIT.

namespace GE
{
    enum class VS { NONE, END };
    enum class PS { NONE, END };
    enum class CS { NONE, END };
    enum class GS { NONE, END };
    enum class HS { NONE, END };
    enum class DS { NONE, END };
}
"@

    $headerContent = if (Test-Path $HeaderFile) { Get-Content -Path $HeaderFile -Raw -Encoding UTF8 } else { $headerTemplate }
    $originalContent = $headerContent

    try {
        $shaderFiles = Get-ChildItem -Path $ShaderDirectory -Filter *.hlsli -Recurse
        $shaderFiles += Get-ChildItem -Path $ShaderDirectory -Filter *.hlsl -Recurse
    } catch {
        Write-Error "Error reading shader directory: $_"
        return
    }

    $shaderPrefixes = @{
        "VS" = "vs_";
        "PS" = "ps_";
        "GS" = "gs_";
        "HS" = "hs_";
        "DS" = "ds_";
        "CS" = "cs_"
    }

    $enumToFileMap = @{}

    foreach ($enumName in $shaderPrefixes.Keys) {
        $prefix = $shaderPrefixes[$enumName]
        $enumRegex = [regex]"(?s)(enum\s+class\s+$enumName\s*\{\s*)([\s\S]*?)(\s*};)"
        $match = $enumRegex.Match($headerContent)

        if (-not $match.Success) { continue }

        $enumBody = $match.Groups[2].Value
        $existingEnums = $enumBody.Split([Environment]::NewLine) | ForEach-Object { $_.Trim() -replace ",", "" -split "//" | Select-Object -First 1 -ExpandProperty Trim } | Where-Object { $_ -ne "" -and $_ -ne "NONE" -and $_ -ne "END" }

        $newEnums = [System.Collections.Generic.List[string]]@()
        $enumToFileMap[$enumName] = @{}

        foreach ($fileInfo in $shaderFiles) {
            $filename = $fileInfo.Name
            if ($filename.StartsWith($prefix)) {
                $baseName = [System.IO.Path]::GetFileNameWithoutExtension($filename).Substring($prefix.Length)
                if ([string]::IsNullOrWhiteSpace($baseName)) { continue }
                $enumValue = $baseName.ToUpper()
                
                $enumToFileMap[$enumName][$enumValue] = $filename

                if ($enumValue -notin $existingEnums) { $newEnums.Add($enumValue) }
            }
        }

        if ($newEnums.Count -gt 0) {
            $allEnumsForType = $existingEnums + $newEnums
            $sortedEnums = $allEnumsForType | Sort-Object -Unique

            $newBodyString = "`n        NONE,`n"
            foreach ($enum in $sortedEnums) { $newBodyString += "        {0},`n" -f $enum }
            $newBodyString += "        END`n    "
            $newFullBlock = "{0}{1}{2}" -f $match.Groups[1].Value, $newBodyString, $match.Groups[3].Value
            $headerContent = $headerContent.Replace($match.Groups[0].Value, $newFullBlock)
        }
    }

    # --- Generate Enum Header File ---
    if ($headerContent -ne $originalContent) {
        Set-Content -Path $outputEnumFile -Value $headerContent -Encoding UTF8 -NoNewline
        Write-Host "Successfully generated enum header file: $outputEnumFile" -ForegroundColor Green
    } else {
        Write-Host "No new enums found. Enum header is up-to-date." -ForegroundColor Yellow
    }

    # --- Generate Mapping Header File ---
    $mapFileContent = @"
#pragma once

// This file is auto-generated by update_shaders.ps1. DO NOT EDIT.

#include "ShaderTypes.generated.h"
#include <string>
#include <unordered_map>

namespace GE
{
"@

    foreach ($enumName in $enumToFileMap.Keys) {
        $mapName = "enumTo" + $enumName + "FileNameMap"
        $mapFileContent += "    inline const std::unordered_map<${enumName}, std::wstring> ${mapName} = {`n"
        
        foreach ($entry in $enumToFileMap[$enumName].GetEnumerator()) {
            $enumValue = $entry.Key
            $fileName = $entry.Value
            $mapFileContent += "        {${enumName}::${enumValue}, L`"${fileName}`"},`n"
        }
        $mapFileContent = $mapFileContent.TrimEnd(",`n") + "`n"
        $mapFileContent += "    };`n`n"
    }

    $mapFileContent += "}
"

    Set-Content -Path $outputMapFile -Value $mapFileContent -Encoding UTF8 -NoNewline
    Write-Host "Successfully generated mapping header file: $outputMapFile" -ForegroundColor Green
}

# --- Execution ---
Generate-ShaderFiles