
#Requires -Version 5.1

<#
.SYNOPSIS
    Scans a directory for shader files and generates a new C++ header file
    with corresponding enum values.
#>

param (
    [string]$ShaderDirectory = (Join-Path $PSScriptRoot '..\Source\GA6thFinal_Framework\Shaders'),
    [string]$HeaderFile = (Join-Path $PSScriptRoot '..\Source\GA6thFinal_Framework\GraphicsEngine\ShaderTypes.h')
)

function Generate-ShaderTypes {
    Write-Host "Starting shader enum generation process..."

    $outputFile = $HeaderFile -replace '\.h$', '.generated.h'
    Write-Host "Output will be generated to: $outputFile"

    $headerTemplate = @"
#pragma once

// This file is auto-generated by update_shaders.ps1. DO NOT EDIT.

namespace GE
{
    enum class VS
    {
        NONE,
        END
    };

    enum class PS
    {
        NONE,
        END
    };

    enum class CS
    {
        NONE,
        END
    };

    enum class GS
    {
        NONE,
        END
    };

    enum class HS
    {
        NONE,
        END
    };

    enum class DS
    {
        NONE,
        END
    };
}
"@

    $headerContent = if (Test-Path $HeaderFile) { Get-Content -Path $HeaderFile -Raw -Encoding UTF8 } else { $headerTemplate }
    $originalContent = $headerContent

    try {
        $shaderFiles = Get-ChildItem -Path $ShaderDirectory -Filter *.hlsli -Recurse -Name
        $shaderFiles += Get-ChildItem -Path $ShaderDirectory -Filter *.hlsl -Recurse -Name
    } catch {
        Write-Error "Error reading shader directory: $_"
        return
    }

    $shaderPrefixes = @{
        "VS" = "vs_";
        "PS" = "ps_";
        "GS" = "gs_";
        "HS" = "hs_";
        "DS" = "ds_";
        "CS" = "cs_"
    }

    foreach ($enumName in $shaderPrefixes.Keys) {
        $prefix = $shaderPrefixes[$enumName]
        
        # Corrected Regex: Use non-greedy matching `*?` and be more specific
        $enumRegex = [regex]"(?s)(enum\s+class\s+$enumName\s*\{\s*)([\s\S]*?)(\s*};)"
        $match = $enumRegex.Match($headerContent)

        if (-not $match.Success) {
            continue
        }

        $enumBody = $match.Groups[2].Value

        $existingEnums = $enumBody.Split([Environment]::NewLine) | ForEach-Object {
            $_.Trim() -replace ",", "" -split "//" | Select-Object -First 1 -ExpandProperty Trim
        } | Where-Object { $_ -ne "" -and $_ -ne "NONE" -and $_ -ne "END" }

        $newEnums = [System.Collections.Generic.List[string]]@()
        foreach ($filename in $shaderFiles) {
            if ($filename.StartsWith($prefix)) {
                $baseName = [System.IO.Path]::GetFileNameWithoutExtension($filename).Substring($prefix.Length)
                if ([string]::IsNullOrWhiteSpace($baseName)) {
                    continue
                }
                $enumValue = $baseName.ToUpper()

                if ($enumValue -notin $existingEnums) {
                    $newEnums.Add($enumValue)
                }
            }
        }

        if ($newEnums.Count -gt 0) {
            $allEnums = $existingEnums + $newEnums
            $sortedEnums = $allEnums | Sort-Object -Unique

            # Rebuild the entire enum body as a single string
            $newBodyString = "`n        NONE,`n"
            foreach ($enum in $sortedEnums) {
                $newBodyString += "        {0},`n" -f $enum
            }
            $newBodyString += "        END`n    "

            # Construct the new full block for replacement
            $newFullBlock = "{0}{1}{2}" -f $match.Groups[1].Value, $newBodyString, $match.Groups[3].Value
            $headerContent = $headerContent.Replace($match.Groups[0].Value, $newFullBlock)
        }
    }

    if ($headerContent -ne $originalContent) {
        try {
            Write-Host "Generating new header file: $outputFile"
            Set-Content -Path $outputFile -Value $headerContent -Encoding UTF8 -NoNewline
            Write-Host "Successfully generated header file." -ForegroundColor Green
        } catch {
            Write-Error "Could not write to the new header file: $_"
        }
    } else {
        Write-Host "No changes detected. The generated file is already up-to-date." -ForegroundColor Yellow
    }
}

# --- Execution ---
Generate-ShaderTypes
