#pragma once
#include "Graphics_Enums.h"

constexpr UINT MAX_BONE_MATRIX        = 256;
constexpr UINT MAX_DIRECTIONAL_LIGHT  = 4;
constexpr UINT MAX_POINT_LIGHT        = 32;
constexpr UINT MAX_SPOT_LIGHT         = 16;
constexpr UINT MAX_LIGHT              = MAX_DIRECTIONAL_LIGHT + MAX_POINT_LIGHT + MAX_SPOT_LIGHT;
constexpr UINT MAX_MIPMAP_LEVEL       = 2;
constexpr UINT MAX_CASCADES           = 4;


enum GBuffer { BASECOLOR, NORMAL, ORM, EMISSIVE, WORLDPOSITION, DEPTH, CUSTOMDEPTH, GBUFFER_END };

enum DXRGBuffer { DXRNORMAL, DXRWORLDPOSITION, DXRDEPTH, DXRCUSTOMDEPTH, DXRGBUFFER_END };

enum FrameResourceType { TRANSFORM, BONE_MATRICES, MATERIAL, UI_TRANSFORM, UI_MATERIAL, VERTEX_BUFFER_ID, INDEX_BUFFER_ID, STATIC_MESH_INSTANCE_ID, SKELETAL_MESH_INSTANCE_ID, FRAME_TYPE_END };