#pragma once
#include "Graphics_Enums.h"

constexpr UINT MAX_BONE_MATRIX        = 256;
constexpr UINT MAX_DIRECTIONAL_LIGHT  = 4;
constexpr UINT MAX_POINT_LIGHT        = 32;
constexpr UINT MAX_SPOT_LIGHT         = 16;
constexpr UINT MAX_LIGHT              = MAX_DIRECTIONAL_LIGHT + MAX_POINT_LIGHT + MAX_SPOT_LIGHT;
constexpr UINT MAX_MIPMAP_LEVEL       = 5;
constexpr UINT MAX_CASCADES           = 4;

// volumetric fog medium
constexpr UINT VOXEL_VOLUME_SIZEX = 240;
constexpr UINT VOXEL_VOLUME_SIZEY = 135;
constexpr UINT VOXEL_VOLUME_SIZEZ = 128;

enum GBuffer { BASECOLOR, NORMAL, ORM, EMISSIVE, DEPTH, CUSTOMDEPTH, GBUFFER_END };

enum DXRGBuffer { DXRNORMAL, DXRDEPTH, DXRCUSTOMDEPTH, DXRGBUFFER_END };

enum FrameResourceType { TRANSFORM, BONE_MATRICES, MATERIAL, UI_TRANSFORM, UI_MATERIAL, VERTEX_BUFFER_ID, INDEX_BUFFER_ID, MESH_INSTANCE_ID, FRAME_TYPE_END };