#pragma once

#include "Device.h"
#include "CommandSet.h"
#include "CommandController.h"
#include "ThreadPool.h"

#include "SharedResource.h"
#include "ConstantBufferView.h"
#include "DepthStencilView.h"
#include "StructuredBuffer.h"
#include "UnorderedAccessView.h"
#include "GraphicsPointer.h"

#include "Texture.h"
#include "Camera.h"
#include "Quad.h"
#include "Model.h"

#include "RenderTarget.h"
#include "RenderScene.h"
#include "RenderTechnique.h"
#include "RenderPassDatas.h"
#include "ShaderBuilder.h"
#include "FX.h"

#include "DXResourceManager.h"
#include "MultiRenderTargetManager.h"
#include "ResourceManager.h"
#include "ViewManager.h"
#include "AccelerationStructureManager.h"
#include "Module/ModuleManager.h"
#include "PipelineStateManager.h"
#include "ParticleManager.h"

#include "SceneTransitionCore.h"
#include "DebugDrawCore.h"
#include "AnimationCore.h"
#include "LightCore.h"
#include "Renderer.h"