#pragma once

// This file is auto-generated by update_shaders.ps1. DO NOT EDIT.

#include "ShaderTypes.generated.h"
#include <string>
#include <unordered_map>

namespace GE
{    inline const std::unordered_map<DS, std::wstring> enumToDSFileNameMap = {
    };

    inline const std::unordered_map<VS, std::wstring> enumToVSFileNameMap = {
        {VS::GRID, L"vs_grid.hlsl"},
        {VS::SKELETAL_FR, L"vs_skeletal_fr.hlsl"},
        {VS::PARTICLE_RIBBON, L"vs_particle_ribbon.hlsl"},
        {VS::STATIC_FR, L"vs_static_fr.hlsl"},
        {VS::SKYBOX, L"vs_skybox.hlsl"},
        {VS::UI_FR, L"vs_ui_fr.hlsl"},
        {VS::PARTICLE_FULLSCREEN, L"vs_particle_fullscreen.hlsl"},
        {VS::QUAD, L"vs_quad.hlsl"},
        {VS::SKELETAL_SHADOW_FR, L"vs_skeletal_shadow_fr.hlsl"},
        {VS::PARTICLE_QUAD, L"vs_particle_quad.hlsl"},
        {VS::STATIC_SHADOW_FR, L"vs_static_shadow_fr.hlsl"}
    };

    inline const std::unordered_map<CS, std::wstring> enumToCSFileNameMap = {
        {CS::COMPUTE_SPRITE, L"cs_compute_sprite.hlsl"},
        {CS::PREFILTERED_MAP, L"cs_prefiltered_map.hlsl"},
        {CS::DEPTH_EXTRACT, L"cs_depth_extract.hlsl"},
        {CS::BRDF_LUT, L"cs_brdf_lut.hlsl"},
        {CS::VALIDATE_SORT, L"cs_validate_sort.hlsl"},
        {CS::PARTICLE_REORDER, L"cs_particle_reorder.hlsl"},
        {CS::RADIX_HISTOGRAM, L"cs_radix_histogram.hlsl"},
        {CS::LIGHT_ACCUMULATION, L"cs_light_accumulation.hlsl"},
        {CS::COMPUTE_RIBBON, L"cs_compute_ribbon.hlsl"},
        {CS::CUBE_TEXTURE_CONVERTOR, L"cs_cube_texture_convertor.hlsl"},
        {CS::IRRADIANCE_MAP, L"cs_irradiance_map.hlsl"},
        {CS::BRDF_LUT, L"cs_brdf_lut.hlsl"},
        {CS::SKELETAL_SKINNING, L"cs_skeletal_skinning.hlsl"},
        {CS::RADIX_SCATTER, L"cs_radix_scatter.hlsl"},
        {CS::COMPUTE_RIBBON, L"cs_compute_ribbon.hlsl"},
        {CS::CUBE_TEXTURE_CONVERTOR, L"cs_cube_texture_convertor.hlsl"},
        {CS::LIGHT_INJECTION, L"cs_light_injection.hlsl"},
        {CS::PREFIX_SUM, L"cs_prefix_sum.hlsl"}
    };

    inline const std::unordered_map<PS, std::wstring> enumToPSFileNameMap = {
        {PS::BLEND, L"ps_blend.hlsl"},
        {PS::WRITE_AO, L"ps_write_ao.hlsl"},
        {PS::PARTICLE_QUAD, L"ps_particle_quad.hlsl"},
        {PS::GAUSSIANBLUR_X, L"ps_gaussianblur_x.hlsl"},
        {PS::TO_BACKBUFFER, L"ps_to_backbuffer.hlsl"},
        {PS::SSR, L"ps_ssr.hlsl"},
        {PS::SKYBOX, L"ps_skybox.hlsl"},
        {PS::UI, L"ps_ui.hlsl"},
        {PS::VOLUMETRIC_FOG, L"ps_volumetric_fog.hlsl"},
        {PS::ACCUMULATION, L"ps_accumulation.hlsl"},
        {PS::DOWN_SAMPLE, L"ps_down_sample.hlsl"},
        {PS::DISTORTION_RESOLVE, L"ps_distortion_resolve.hlsl"},
        {PS::GAUSSIANBLUR_Y, L"ps_gaussianblur_y.hlsl"},
        {PS::PARTICLE_RESOLVE, L"ps_particle_resolve.hlsl"},
        {PS::OUTLINE, L"ps_outline.hlsl"},
        {PS::GRID, L"ps_grid.hlsl"},
        {PS::GBUFFER, L"ps_gbuffer.hlsl"},
        {PS::PBR_LIGHTING, L"ps_pbr_lighting.hlsl"},
        {PS::BRIGHT_EXTRACT, L"ps_bright_extract.hlsl"},
        {PS::UP_SAMPLE, L"ps_up_sample.hlsl"},
        {PS::DXRGBUFFER, L"ps_dxrgbuffer.hlsl"}
    };

    inline const std::unordered_map<HS, std::wstring> enumToHSFileNameMap = {
    };

    inline const std::unordered_map<GS, std::wstring> enumToGSFileNameMap = {
    };

}
