#pragma once

#ifdef NDEBUG
// This file is auto-generated by update_shaders.ps1. DO NOT EDIT.

#include "ShaderTypes.generated.h"
#include "Shaders/CompiledShaders.h"
#include <d3d12.h>

namespace GE
{
    inline D3D12_SHADER_BYTECODE GetShaderBytecode(PS shader)
    {
        switch (shader)
        {            case PS::ACCUMULATION: return { g_ps_accumulation, sizeof(g_ps_accumulation) };
            case PS::BILATERAL_UP_SAMPLE: return { g_ps_bilateral_up_sample, sizeof(g_ps_bilateral_up_sample) };
            case PS::BLEND: return { g_ps_blend, sizeof(g_ps_blend) };
            case PS::BRIGHT_EXTRACT: return { g_ps_bright_extract, sizeof(g_ps_bright_extract) };
            case PS::BURN_DISSOLVE: return { g_ps_burn_dissolve, sizeof(g_ps_burn_dissolve) };
            case PS::DISTORTION_RESOLVE: return { g_ps_distortion_resolve, sizeof(g_ps_distortion_resolve) };
            case PS::DOWN_SAMPLE: return { g_ps_down_sample, sizeof(g_ps_down_sample) };
            case PS::DXRGBUFFER: return { g_ps_dxrgbuffer, sizeof(g_ps_dxrgbuffer) };
            case PS::FADE: return { g_ps_fade, sizeof(g_ps_fade) };
            case PS::FORWARD_PBR_LIGHTING: return { g_ps_forward_pbr_lighting, sizeof(g_ps_forward_pbr_lighting) };
            case PS::FXAA: return { g_ps_fxaa, sizeof(g_ps_fxaa) };
            case PS::GAUSSIANBLUR_X: return { g_ps_gaussianblur_x, sizeof(g_ps_gaussianblur_x) };
            case PS::GAUSSIANBLUR_Y: return { g_ps_gaussianblur_y, sizeof(g_ps_gaussianblur_y) };
            case PS::GBUFFER: return { g_ps_gbuffer, sizeof(g_ps_gbuffer) };
            case PS::GBUFFER_MASKED: return { g_ps_gbuffer_masked, sizeof(g_ps_gbuffer_masked) };
            case PS::GRID: return { g_ps_grid, sizeof(g_ps_grid) };
            case PS::OUTLINE: return { g_ps_outline, sizeof(g_ps_outline) };
            case PS::PARTICLE_QUAD: return { g_ps_particle_quad, sizeof(g_ps_particle_quad) };
            case PS::PARTICLE_RESOLVE: return { g_ps_particle_resolve, sizeof(g_ps_particle_resolve) };
            case PS::PBR_LIGHTING: return { g_ps_pbr_lighting, sizeof(g_ps_pbr_lighting) };
            case PS::POINT_LIGHT_SHADOW: return { g_ps_point_light_shadow, sizeof(g_ps_point_light_shadow) };
            case PS::SDF_FONT: return { g_ps_sdf_font, sizeof(g_ps_sdf_font) };
            case PS::SHADOW: return { g_ps_shadow, sizeof(g_ps_shadow) };
            case PS::SKYBOX: return { g_ps_skybox, sizeof(g_ps_skybox) };
            case PS::SSGI_COMPOSITE: return { g_ps_ssgi_composite, sizeof(g_ps_ssgi_composite) };
            case PS::SSR: return { g_ps_ssr, sizeof(g_ps_ssr) };
            case PS::TO_BACKBUFFER: return { g_ps_to_backbuffer, sizeof(g_ps_to_backbuffer) };
            case PS::TRANSPARENT_LIM_LIGHT: return { g_ps_transparent_lim_light, sizeof(g_ps_transparent_lim_light) };
            case PS::UI: return { g_ps_ui, sizeof(g_ps_ui) };
            case PS::UI_OIT: return { g_ps_ui_oit, sizeof(g_ps_ui_oit) };
            case PS::UP_SAMPLE: return { g_ps_up_sample, sizeof(g_ps_up_sample) };
            case PS::VOLUMETRIC_FOG: return { g_ps_volumetric_fog, sizeof(g_ps_volumetric_fog) };
            case PS::WRITE_AO: return { g_ps_write_ao, sizeof(g_ps_write_ao) };
            default: return { nullptr, 0 };
        }
    }
    inline D3D12_SHADER_BYTECODE GetShaderBytecode(VS shader)
    {
        switch (shader)
        {            case VS::GRID: return { g_vs_grid, sizeof(g_vs_grid) };
            case VS::PARTICLE_FULLSCREEN: return { g_vs_particle_fullscreen, sizeof(g_vs_particle_fullscreen) };
            case VS::PARTICLE_QUAD: return { g_vs_particle_quad, sizeof(g_vs_particle_quad) };
            case VS::PARTICLE_RIBBON: return { g_vs_particle_ribbon, sizeof(g_vs_particle_ribbon) };
            case VS::QUAD: return { g_vs_quad, sizeof(g_vs_quad) };
            case VS::SDF_FONT_FR: return { g_vs_sdf_font_fr, sizeof(g_vs_sdf_font_fr) };
            case VS::SKELETAL_FORWARD_FR: return { g_vs_skeletal_forward_fr, sizeof(g_vs_skeletal_forward_fr) };
            case VS::SKELETAL_FR: return { g_vs_skeletal_fr, sizeof(g_vs_skeletal_fr) };
            case VS::SKELETAL_POINT_LIGHT_SHADOW_FR: return { g_vs_skeletal_point_light_shadow_fr, sizeof(g_vs_skeletal_point_light_shadow_fr) };
            case VS::SKELETAL_SHADOW_FR: return { g_vs_skeletal_shadow_fr, sizeof(g_vs_skeletal_shadow_fr) };
            case VS::SKYBOX: return { g_vs_skybox, sizeof(g_vs_skybox) };
            case VS::STATIC_FORWARD_FR: return { g_vs_static_forward_fr, sizeof(g_vs_static_forward_fr) };
            case VS::STATIC_FR: return { g_vs_static_fr, sizeof(g_vs_static_fr) };
            case VS::STATIC_POINT_LIGHT_SHADOW_FR: return { g_vs_static_point_light_shadow_fr, sizeof(g_vs_static_point_light_shadow_fr) };
            case VS::STATIC_SHADOW_FR: return { g_vs_static_shadow_fr, sizeof(g_vs_static_shadow_fr) };
            case VS::UI_FR: return { g_vs_ui_fr, sizeof(g_vs_ui_fr) };
            default: return { nullptr, 0 };
        }
    }
    inline D3D12_SHADER_BYTECODE GetShaderBytecode(CS shader)
    {
        switch (shader)
        {            case CS::BRDF_LUT: return { g_cs_brdf_lut, sizeof(g_cs_brdf_lut) };
            case CS::CALCULATE_MOTION_VECTOR: return { g_cs_calculate_motion_vector, sizeof(g_cs_calculate_motion_vector) };
            case CS::COMPUTE_RIBBON: return { g_cs_compute_ribbon, sizeof(g_cs_compute_ribbon) };
            case CS::COMPUTE_SPRITE: return { g_cs_compute_sprite, sizeof(g_cs_compute_sprite) };
            case CS::CUBE_TEXTURE_CONVERTOR: return { g_cs_cube_texture_convertor, sizeof(g_cs_cube_texture_convertor) };
            case CS::GENERATE_SSGI: return { g_cs_generate_ssgi, sizeof(g_cs_generate_ssgi) };
            case CS::IRRADIANCE_MAP: return { g_cs_irradiance_map, sizeof(g_cs_irradiance_map) };
            case CS::LIGHT_ACCUMULATION: return { g_cs_light_accumulation, sizeof(g_cs_light_accumulation) };
            case CS::LIGHT_INJECTION: return { g_cs_light_injection, sizeof(g_cs_light_injection) };
            case CS::PREFILTERED_MAP: return { g_cs_prefiltered_map, sizeof(g_cs_prefiltered_map) };
            case CS::RESOLVE_UI: return { g_cs_resolve_ui, sizeof(g_cs_resolve_ui) };
            case CS::SKELETAL_SKINNING: return { g_cs_skeletal_skinning, sizeof(g_cs_skeletal_skinning) };
            case CS::SSGI_TEMPORAL: return { g_cs_ssgi_temporal, sizeof(g_cs_ssgi_temporal) };
            default: return { nullptr, 0 };
        }
    }}
#endif