name: Bump Version on PR to Develop

on:
  pull_request:    
    types:
      - closed
    branches:
      - develop

jobs:
  bump-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Git identity
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"

    - name: Decide version bump type
      id: bump
      run: |
        BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
        echo "Source branch: $BRANCH_NAME"

        if [[ "$BRANCH_NAME" == feature/* ]]; then
          echo "version=minor" >> $GITHUB_OUTPUT
        elif [[ "$BRANCH_NAME" == fix/* || "$BRANCH_NAME" == hotfix/* ]]; then
          echo "version=patch" >> $GITHUB_OUTPUT
        else
          echo "version=none" >> $GITHUB_OUTPUT
        fi

    - name: Calculate new version
      id: version
      run: |
        chmod +x ./scripts/bump-${{ steps.bump.outputs.version }}.sh
        new_version=$(./scripts/bump-${{ steps.bump.outputs.version }}.sh)
        echo "new_version=$new_version" >> $GITHUB_OUTPUT

    - name: Tag the version
      if: steps.bump.outputs.version != 'none'
      run: |
        git tag ${{ steps.version.outputs.new_version }}
        git push origin ${{ steps.version.outputs.new_version }}
